version: '3.3.0'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: bloomberg
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD:

    ports:
      - "3306:3306"

  backend:
    build:
      context: ./GetDressed
      dockerfile: Dockerfile

    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/bloomberg?createDatabaseIfNotExist=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD:
    depends_on:
      - mysql
