# Server Configuration
server:
  port: 8082
  error:
    include-message: always
    include-binding-errors: always

# Spring Configuration
spring:
  main:
    allow-circular-references: true
  # to enable colors when you run your app outside IntelliJ
  output:
    ansi:
      enabled: always
  # Database Configuration
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true